### PR TITLE
feat(linter): add ruff adapters

### LINKED ISSUE #32: Ruff adapter
https://github.com/charliermarsh/ruff

### PR DESCRIPTION
**Pull request by q0w**
[charliermarsh/ruff](https://github.com/charliermarsh/ruff)

I am not sure what to use as char in LintMessage - column in `location` or column in `end_location` of the ruff report output.

To enable autoformatting its possible to use `fix=true` in pyproject.toml

Closes #32

### CODE REVIEW

**Comment by justinchuby** [comment]
When fix=true are files always formatted? I wonder if it is possible to use lintrunner’s format mechanism to emit a formatted version for each file. It’s ok to trade some speed for more control if possible I think.

**Comment by q0w** [comment]
No, its not possible, because stdout is empty with `--fix` arg, as ruff does not return diff

**Comment by q0w** [comment]
hmm, maybe is possible with `--stdin-filename` but it would more slow

**Comment by q0w** [comment]
With --fix ruff does not return violations

**Comment by justinchuby** [comment]
I would be great to make use of the --stdin-filename option. Or we can also have two adapters. One is faster and native ruff, the other allows more control for fix with file by file replacement

**Comment by q0w** [comment]
So to use  lintrunner’s format mechanism, we should first call ruff without --fix to get violations, then call ruff with --fix to get replacement content

**Comment by q0w** [comment]
Or we could implement formatting as ruff_format_linter.py

**Comment by q0w** [comment]
I've tried several solutions:
1. one adapter to lint all files once and second adapter to fix file by file
2. one adapter to lint all files once and to fix file by file
3. one adapter to lint and fix file by file

Every time ruff was ouf sync - it reports violations after autoformatting (using lintrunner -a)

**Comment by q0w** [comment]
ruff_fix_linter is 60x slower

**Review by justinchuby — APPROVED** [review]
Thank you so much! Being able to support ruff is great. I am curious if the slowdown is caused mainly by Python overhead. I will take a closer look as well

**Comment by justinchuby** [comment]
> I am not sure what to use as char in LintMessage - column in `location` or column in `end_location` of the ruff report output.

I’d say use location for now?

**Pull request merged**
