### PR TITLE
fix: ruff-fix display all lint errors; enable ruff and format all files

### PR DESCRIPTION
**Pull request by justinchuby**
Update ruff-fix to fix errors only, so that it runs faster and can be used in combination with RUFF. Set ruff default error level to warning.

RUFF-FIX is still much faster than flake8 (~400ms vs 4.6s), which I am happy about.

cc @q0w

### CODE REVIEW

**Comment by q0w** [comment]
Using original content would cause showing errors after applying patches (lintrunner -a). Is it ok? Then you should call lintrunner twice

**Comment by justinchuby** [comment]
> Using original content would cause showing errors after applying patches (lintrunner -a). Is it ok? Then you should call lintrunner twice

Hmm you are right. But I think that's the best we can get (that I can think of). I thought of using both RUFF and RUFF-FIX but that would give us the same result with `-a`. I think in this case being able to see the errors is more important?

**Comment by justinchuby** [comment]
CI isn't happy for some reason

**Comment by q0w** [comment]
So we can remove `ruff check` from ruff_fix_linter, if we should use both ruff_linter and ruff_fix_linter

**Comment by justinchuby** [comment]
How is ruff and ruff check different?

**Comment by q0w** [comment]
We could use ruff_linter to lint errors and `ruff_fix_linter only to format files`

**Comment by justinchuby** [comment]
That's a great idea thanks!

**Comment by justinchuby** [comment]
> Using original content would cause showing errors after applying patches (lintrunner -a). Is it ok? Then you should call lintrunner twice

Related https://github.com/suo/lintrunner/issues/24

**Pull request merged**
